# Generated by Django 4.1.2 on 2024-05-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sstempresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresasst',
            name='archivo',
            field=models.FileField(upload_to='adjuntos_empresaSST/'),
        ),
    ]
