# Generated by Django 4.1.2 on 2024-04-23 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonasSST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('Perfil sociodemográfico', 'Perfil sociodemográfico'), ('Análisis de puesto de trabajo', 'Análisis de puesto de trabajo'), ('Exámenes médicos', 'Exámenes médicos'), ('Otros', 'Otros')], max_length=50, verbose_name='Tipo de Documento')),
                ('nombre_documento', models.CharField(max_length=255, verbose_name='Nombre del Documento')),
                ('archivo', models.FileField(upload_to='adjuntos_personaSST/')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('persona_SST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.persona')),
            ],
        ),
    ]
