# Generated by Django 4.1.2 on 2024-05-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_alter_contrato_cargo_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='celular_representante_legal',
            field=models.CharField(default='+57 320 8434390', max_length=20),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='correo_representante_legal',
            field=models.EmailField(default='jcifuentes@dbcw.com.co', max_length=255, verbose_name='Correo electrónico representante legal'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='direccion_notificacion_judicial',
            field=models.CharField(default='Calle 8 #3-42', max_length=255, verbose_name='Dirección de notificación judicial'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Terminado', 'Terminado'), ('Vencido', 'Vencido'), ('Por vencer', 'Por vencer'), ('Liquidado', 'Liquidado')], default='Activo', max_length=100),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='lugar_expedicion_doc_representante_legal',
            field=models.CharField(default='Bogotá', max_length=255, verbose_name='Lugar expedición doc representante legal'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='nit_empresa',
            field=models.CharField(default='901481430-5', max_length=20),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='numero_doc_representante_legal',
            field=models.CharField(default='1016019519', max_length=20, verbose_name='Número doc representante legal'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='razón_social',
            field=models.CharField(default='DIGITAL BRIDGE COMMUNICATIONS', max_length=255, verbose_name='Razón social'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='ubicacion',
            field=models.CharField(default='Jenesano-Boyacá', max_length=255, verbose_name='Ubicación'),
        ),
    ]
