# Generated by Django 4.1.2 on 2024-06-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0003_alter_contrato_celular_representante_legal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='dias_restantes',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
