# Generated by Django 4.1.2 on 2024-06-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_contrato_dias_restantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='consecutivo',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
