# Generated by Django 4.1.2 on 2024-06-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0005_contrato_consecutivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='tipo_doc_representante_legal',
            field=models.CharField(blank=True, choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('P', 'Pasaporte')], default='', max_length=255),
        ),
    ]
