# Generated by Django 4.1.2 on 2024-06-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0006_alter_contrato_tipo_doc_representante_legal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='tipo_doc_representante_legal',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('P', 'Pasaporte')], default='CC', max_length=255),
        ),
    ]
