# Generated by Django 4.1.2 on 2024-06-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0007_alter_contrato_tipo_doc_representante_legal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='consecutivo',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='dias_restantes',
        ),
        migrations.AlterField(
            model_name='contrato',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Terminado', 'Terminado')], default='Activo', max_length=100),
        ),
    ]
