# Generated by Django 4.1.2 on 2024-06-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0008_remove_contrato_consecutivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='consecutivo',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='dias_restantes',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Terminado', 'Terminado'), ('Vencido', 'Vencido'), ('Por vencer', 'Por vencer'), ('Liquidado', 'Liquidado')], default='Activo', max_length=100),
        ),
    ]
