# Generated by Django 4.1.2 on 2024-05-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0010_remove_contrato_fecha_carga_adjunto_preaviso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='tipo_doc_representante_legal',
            field=models.CharField(default='CC', max_length=20, verbose_name='Tipo doc representante legal'),
        ),
    ]
