# Generated by Django 4.1.2 on 2024-07-22 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0001_initial'),
        ('personas', '0001_initial'),
        ('contratos', '0011_alter_contrato_tipo_doc_representante_legal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='cargo_contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cargos.cargo'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personas.persona'),
        ),
    ]
