# Generated by Django 4.1.2 on 2024-07-31 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0012_alter_contrato_cargo_contrato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='fecha_publicacion_preaviso',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
