# Generated by Django 4.1.2 on 2024-07-31 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0013_contrato_fecha_publicacion_preaviso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='fecha_publicacion_preaviso',
            field=models.DateField(blank=True, null=True),
        ),
    ]
