# Generated by Django 4.1.2 on 2024-08-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0014_alter_contrato_fecha_publicacion_preaviso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='salario',
            field=models.CharField(max_length=15),
        ),
    ]
