# Generated by Django 4.1.2 on 2024-04-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_persona', models.CharField(max_length=255)),
                ('tipo_documento_persona', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('P', 'Pasaporte')], max_length=2)),
                ('numero_documento_persona', models.CharField(max_length=20)),
                ('correo_persona', models.EmailField(max_length=254)),
                ('celular_persona', models.CharField(max_length=20)),
                ('direccion_residencia_persona', models.CharField(max_length=255)),
            ],
        ),
    ]
